site_name: "sendou.py"
repo_url: "https://github.com/IPLSplatoon/sendou.py"
site_dir: "docs"

plugins:
  - autorefs
  - search
  - gen-files:
      scripts:
        - scripts/genRefPages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
theme:
  name: material
  nav:
    - Overview: index.md
    - Getting Started:
      - Installation: getting-started/installation.md
      - Usage Guide: getting-started/usageGuide.md
    - Cache Configuration: cacheConfig.md
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
- attr_list
- admonition
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: "¤"
